import { db } from "./db";
import { users, workers, jobs, messages } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  const existingUsers = await db.select().from(users);
  if (existingUsers.length > 0) return;

  const seedUsers = await db.insert(users).values([
    {
      username: "alex_m",
      password: "hashed_password",
      fullName: "Alex Mehmet",
      email: "alex@mapable.com.au",
      role: "carer",
      location: "Parramatta, NSW",
      bio: "Experienced support worker with 5 years in NDIS services. Passionate about community access and transport assistance.",
      languages: ["English", "Arabic"],
      skills: ["Manual Handling", "Transport", "Community Access"],
      isVerified: true,
    },
    {
      username: "sam_t",
      password: "hashed_password",
      fullName: "Sam Thompson",
      email: "sam@mapable.com.au",
      role: "carer",
      location: "Blacktown, NSW",
      bio: "Dedicated carer specializing in personal care and domestic assistance. Auslan proficient.",
      languages: ["English", "Auslan"],
      skills: ["Personal Care", "Domestic Assistance", "Auslan"],
      isVerified: true,
    },
    {
      username: "sarah_j",
      password: "hashed_password",
      fullName: "Sarah Johnson",
      email: "sarah@mapable.com.au",
      role: "carer",
      location: "Bondi, NSW",
      bio: "Qualified support worker with expertise in wheelchair transport and meal preparation.",
      languages: ["English"],
      skills: ["Transport", "Meal Prep", "Personal Care"],
      isVerified: true,
    },
    {
      username: "priya_k",
      password: "hashed_password",
      fullName: "Priya Kumar",
      email: "priya@mapable.com.au",
      role: "carer",
      location: "Parramatta, NSW",
      bio: "Cultural safety specialist with deep understanding of diverse community needs.",
      languages: ["English", "Hindi", "Tamil"],
      skills: ["Cultural Safety", "Community Access", "Social Support"],
      isVerified: true,
    },
    {
      username: "liam_w",
      password: "hashed_password",
      fullName: "Liam Wilson",
      email: "liam@mapable.com.au",
      role: "carer",
      location: "Liverpool, NSW",
      bio: "Sports and recreation support worker. Helping participants stay active and engaged.",
      languages: ["English"],
      skills: ["Recreation", "Exercise Physiology", "Community Access"],
      isVerified: true,
    },
    {
      username: "demo_participant",
      password: "hashed_password",
      fullName: "Jordan Lee",
      email: "jordan@example.com",
      role: "participant",
      location: "Sydney, NSW",
      accessNeeds: ["Wheelchair Accessible", "Low Sensory Environment"],
    },
    {
      username: "ndis_provider",
      password: "hashed_password",
      fullName: "MapAble Services",
      email: "services@mapable.com.au",
      role: "provider",
      location: "Sydney, NSW",
    },
  ]).returning();

  const carerIds = seedUsers.filter(u => u.role === "carer");

  await db.insert(workers).values([
    {
      userId: carerIds[0].id,
      title: "Senior Support Worker & Transport Driver",
      specializations: ["Manual Handling", "Community Access", "Transport", "Personal Care"],
      hourlyRate: "55.00",
      transportCapable: true,
      transportType: "Car, Wheelchair Accessible",
      wheelchairAccessible: true,
      ndisVerified: true,
      rating: "4.80",
      reviewCount: 47,
      availability: "Mon-Fri, 7am-6pm",
    },
    {
      userId: carerIds[1].id,
      title: "Personal Care & Auslan Interpreter",
      specializations: ["Personal Care", "Auslan", "Domestic Assistance", "Meal Prep"],
      hourlyRate: "52.00",
      transportCapable: true,
      transportType: "Car",
      wheelchairAccessible: false,
      ndisVerified: true,
      rating: "4.90",
      reviewCount: 62,
      availability: "Mon-Sat, 8am-8pm",
    },
    {
      userId: carerIds[2].id,
      title: "Transport & Domestic Support Worker",
      specializations: ["Transport", "Meal Prep", "Personal Care", "Shopping Assistance"],
      hourlyRate: "50.00",
      transportCapable: true,
      transportType: "Car, Wheelchair Accessible",
      wheelchairAccessible: true,
      ndisVerified: true,
      rating: "4.70",
      reviewCount: 35,
      availability: "Tue-Sun, 6am-4pm",
    },
    {
      userId: carerIds[3].id,
      title: "Cultural Safety & Community Worker",
      specializations: ["Cultural Safety", "Community Access", "Social Support", "Advocacy"],
      hourlyRate: "48.00",
      transportCapable: false,
      wheelchairAccessible: false,
      ndisVerified: true,
      rating: "4.95",
      reviewCount: 78,
      availability: "Mon-Fri, 9am-5pm",
    },
    {
      userId: carerIds[4].id,
      title: "Recreation & Active Support Worker",
      specializations: ["Recreation", "Exercise Physiology", "Community Access", "Group Activities"],
      hourlyRate: "53.00",
      transportCapable: true,
      transportType: "Car",
      wheelchairAccessible: false,
      ndisVerified: true,
      rating: "4.85",
      reviewCount: 41,
      availability: "Mon-Sun, flexible",
    },
  ]);

  await db.insert(jobs).values([
    {
      postedBy: seedUsers.find(u => u.role === "provider")!.id,
      title: "Support Worker - Personal Care",
      description: "Seeking compassionate support workers for personal care services across Western Sydney. Must have NDIS Worker Screening clearance and experience with manual handling.",
      location: "Western Sydney, NSW",
      jobType: "Part-time",
      salary: "$32-$38/hr",
      requirements: ["NDIS Worker Screening", "First Aid Certificate", "Manual Handling"],
      category: "Care",
      status: "open",
    },
    {
      postedBy: seedUsers.find(u => u.role === "provider")!.id,
      title: "Transport Driver - NDIS Participants",
      description: "Looking for reliable drivers to provide transport services for NDIS participants. Wheelchair accessible vehicle is a plus. Flexible hours available.",
      location: "Sydney Metro, NSW",
      jobType: "Casual",
      salary: "$35-$42/hr",
      requirements: ["Driver Licence", "NDIS Worker Screening", "Working with Children Check"],
      category: "Transport",
      status: "open",
    },
    {
      postedBy: seedUsers.find(u => u.role === "provider")!.id,
      title: "Community Access Coordinator",
      description: "Full-time role coordinating community access programs for NDIS participants. You will plan and deliver inclusive activities and build community partnerships.",
      location: "Parramatta, NSW",
      jobType: "Full-time",
      salary: "$65,000 - $75,000",
      requirements: ["Certificate IV in Disability", "NDIS Experience", "Driver Licence"],
      category: "Support",
      status: "open",
    },
    {
      postedBy: seedUsers.find(u => u.role === "provider")!.id,
      title: "Auslan Interpreter - Support Services",
      description: "Seeking qualified Auslan interpreters to support Deaf and hard of hearing NDIS participants in appointments, community activities, and daily living tasks.",
      location: "Sydney CBD, NSW",
      jobType: "Contract",
      salary: "$45-$55/hr",
      requirements: ["NAATI Accredited", "NDIS Worker Screening", "Auslan Proficiency"],
      category: "Care",
      status: "open",
    },
    {
      postedBy: seedUsers.find(u => u.role === "provider")!.id,
      title: "Disability Employment Consultant",
      description: "Join our team helping NDIS participants find meaningful employment. You will provide career coaching, workplace modifications advice, and employer engagement.",
      location: "Sydney, NSW",
      jobType: "Full-time",
      salary: "$70,000 - $85,000",
      requirements: ["Employment Services Experience", "NDIS Knowledge", "Cert IV in Employment Services"],
      category: "Employment",
      status: "open",
    },
  ]);

  await db.insert(messages).values([
    {
      senderId: carerIds[0].id,
      receiverId: seedUsers.find(u => u.role === "participant")!.id,
      body: "Hi Jordan! I am available for your transport request on Thursday. I have a wheelchair accessible vehicle. Let me know if you would like to confirm.",
    },
    {
      senderId: seedUsers.find(u => u.role === "participant")!.id,
      receiverId: carerIds[0].id,
      body: "That sounds great Alex! Can we schedule for 10am pickup from Parramatta station?",
    },
    {
      senderId: carerIds[1].id,
      receiverId: seedUsers.find(u => u.role === "participant")!.id,
      body: "Hi! I saw you were looking for a support worker who knows Auslan. I am NAATI certified and available on weekdays. Would you like to chat about your needs?",
    },
  ]);

  console.log("Database seeded successfully");
}
